const fs = require('fs');
const path = require('path');

module.exports = async function handler(req, res) {
  // CORS Headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Content-Type', 'application/json');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ status: 'error', message: 'Method Not Allowed' });
  }

  try {
    let newSchedules = req.body;
    if (typeof newSchedules === 'string') {
      try {
        newSchedules = JSON.parse(newSchedules);
      } catch (e) {
        return res.status(400).json({ status: 'error', message: 'Invalid JSON body' });
      }
    }

    if (!newSchedules || !Array.isArray(newSchedules)) {
      return res.status(400).json({ status: 'error', message: 'Invalid schedule data structure' });
    }

    const supabaseUrl = process.env.SUPABASE_URL;
    const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;

    // Log environment variables check (safe logging)
    console.log('=== SUPABASE ENV CHECK ===');
    console.log('SUPABASE_URL exists:', !!supabaseUrl);
    if (supabaseUrl) {
      console.log('SUPABASE_URL value:', supabaseUrl);
    }
    console.log('SUPABASE_ANON_KEY exists:', !!supabaseAnonKey);
    if (supabaseAnonKey) {
      console.log('SUPABASE_ANON_KEY length:', supabaseAnonKey.length);
      // Log the first 15 chars to help debug incorrect formats (e.g. multi-line copies)
      const sanitizedKey = supabaseAnonKey.replace(/[\r\n]/g, '\\n');
      console.log('SUPABASE_ANON_KEY starts with:', sanitizedKey.substring(0, 15) + '...');
    }
    console.log('==========================');

    if (!supabaseUrl || !supabaseAnonKey) {
      return res.status(500).json({
        status: 'error',
        message: 'Supabase 환경변수가 없습니다. Vercel 프로젝트 설정에서 SUPABASE_URL과 SUPABASE_ANON_KEY가 설정되었는지 확인해 주세요.'
      });
    }

    // 1. Clear Supabase schedules table
    const deleteUrl = `${supabaseUrl}/rest/v1/schedules?id=not.is.null`;
    const deleteResp = await fetch(deleteUrl, {
      method: 'DELETE',
      headers: {
        'apikey': supabaseAnonKey,
        'Authorization': `Bearer ${supabaseAnonKey}`
      }
    });
    if (!deleteResp.ok) {
      const deleteErr = await deleteResp.text();
      return res.status(500).json({ status: 'error', message: `Supabase clear failed: ${deleteErr}` });
    }

    // 2. Insert new records in bulk
    const payload = newSchedules.map(s => ({
      member: s.member || '',
      date: s.date || '',
      day: s.day || '',
      time: s.time || '미정',
      title: s.title || '',
      note: s.note || '',
      source: s.source || 'manual',
      url: s.url || ''
    }));

    const insertUrl = `${supabaseUrl}/rest/v1/schedules`;
    const insertResp = await fetch(insertUrl, {
      method: 'POST',
      headers: {
        'apikey': supabaseAnonKey,
        'Authorization': `Bearer ${supabaseAnonKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(payload)
    });
    if (!insertResp.ok) {
      const insertErr = await insertResp.text();
      return res.status(500).json({ status: 'error', message: `Supabase insert failed: ${insertErr}` });
    }

    // 3. Try to write local data.js cache (fails silently if read-only)
    try {
      const dataJsPath = path.join(process.cwd(), 'data.js');
      const configPath = path.join(process.cwd(), 'config.json');
      let config = {};
      if (fs.existsSync(configPath)) {
        config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
      }
      const configJs = JSON.stringify(config);
      const schedJs = JSON.stringify(newSchedules);
      const nowStr = new Date().toISOString().replace('T', ' ').substring(0, 19);
      const jsContent = `// Auto-generated by serverless api/save_schedule.js — DO NOT EDIT MANUALLY
// Generated: ${nowStr}
window.APP_CONFIG   = ${configJs};
window.APP_SCHEDULE = ${schedJs};
`;
      fs.writeFileSync(dataJsPath, jsContent, 'utf8');
    } catch (writeErr) {
      // Ignore write failures in read-only environment
    }

    return res.status(200).json({ status: 'ok' });
  } catch (err) {
    return res.status(500).json({ status: 'error', message: err.message });
  }
};
