const fs = require('fs');
const path = require('path');

module.exports = async function handler(req, res) {
  // CORS Headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Content-Type', 'application/json');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ status: 'error', message: 'Method Not Allowed' });
  }

  try {
    let newSchedules = req.body;
    if (typeof newSchedules === 'string') {
      try {
        newSchedules = JSON.parse(newSchedules);
      } catch (e) {
        return res.status(400).json({ status: 'error', message: 'Invalid JSON body' });
      }
    }

    if (!newSchedules || !Array.isArray(newSchedules)) {
      return res.status(400).json({ status: 'error', message: 'Invalid schedule data structure' });
    }

    const schedulePath = path.join(process.cwd(), 'schedule.json');
    const configPath = path.join(process.cwd(), 'config.json');
    const dataJsPath = path.join(process.cwd(), 'data.js');

    // 1. Try to write to schedule.json
    try {
      fs.writeFileSync(schedulePath, JSON.stringify(newSchedules, null, 2), 'utf8');
    } catch (writeErr) {
      console.error('Failed to write schedule.json:', writeErr);
      return res.status(403).json({
        status: 'error',
        message: 'Vercel 배포 환경(읽기 전용 파일 시스템)에서는 일정을 직접 저장할 수 없습니다. 로컬 서버(python server.py)를 실행해 수정한 후 깃허브에 커밋하여 반영해 주세요.'
      });
    }

    // 2. Read config.json
    let config = {};
    if (fs.existsSync(configPath)) {
      try {
        config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
      } catch (e) {
        console.error('Failed to parse config.json:', e);
      }
    }

    // 3. Write data.js
    const configJs = JSON.stringify(config);
    const schedJs = JSON.stringify(newSchedules);
    const nowStr = new Date().toISOString().replace('T', ' ').substring(0, 19);
    
    const jsContent = `// Auto-generated by serverless api/save_schedule.js — DO NOT EDIT MANUALLY
// Generated: ${nowStr}
window.APP_CONFIG   = ${configJs};
window.APP_SCHEDULE = ${schedJs};
`;
    try {
      fs.writeFileSync(dataJsPath, jsContent, 'utf8');
    } catch (writeErr) {
      console.error('Failed to write data.js:', writeErr);
    }

    return res.status(200).json({ status: 'ok' });
  } catch (err) {
    return res.status(500).json({ status: 'error', message: err.message });
  }
};
